In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
len(os.listdir('../data/structures'))

130789

In [3]:
train = pd.read_csv('../data/train.csv')
train

,id,molecule_name,atom_index_0,atom_index_1,type,scalar_coupling_constant
0,0,dsgdb9nsd_000001,1,0,1JHC,84.807600
1,1,dsgdb9nsd_000001,1,2,2JHH,-11.257000
2,2,dsgdb9nsd_000001,1,3,2JHH,-11.254800
3,3,dsgdb9nsd_000001,1,4,2JHH,-11.254300
4,4,dsgdb9nsd_000001,2,0,1JHC,84.807400
...,...,...,...,...,...,...
4659071,4659071,dsgdb9nsd_133884,17,4,2JHC,3.543450
4659072,4659072,dsgdb9nsd_133884,17,5,3JHC,0.568997
4659073,4659073,dsgdb9nsd_133884,17,6,3JHC,1.173370
4659074,4659074,dsgdb9nsd_133884,17,7,2JHC,4.762010
4659075,4659075,dsgdb9nsd_133884,17,8,1JHC,117.934000

In [4]:
len(list(set(train.molecule_name.to_list())))

85012

In [5]:
test = pd.read_csv('../data/test.csv')
test

              id     molecule_name  atom_index_0  atom_index_1  type
0        4659076  dsgdb9nsd_000004             2             0  2JHC
1        4659077  dsgdb9nsd_000004             2             1  1JHC
2        4659078  dsgdb9nsd_000004             2             3  3JHH
3        4659079  dsgdb9nsd_000004             3             0  1JHC
4        4659080  dsgdb9nsd_000004             3             1  2JHC
...          ...               ...           ...           ...   ...
2505185  7164261  dsgdb9nsd_133885            15             3  2JHC
2505186  7164262  dsgdb9nsd_133885            15             4  2JHC
2505187  7164263  dsgdb9nsd_133885            15             6  3JHC
2505188  7164264  dsgdb9nsd_133885            15             7  2JHC
2505189  7164265  dsgdb9nsd_133885            15             8  1JHC

[2505190 rows x 5 columns]

In [6]:
len(list(set(test.molecule_name.to_list())))

45777

In [7]:
diapole_moments = pd.read_csv(os.path.join("..","data","dipole_moments.csv"))
magnetic_sheilding_tensors = pd.read_csv(os.path.join("..","data","magnetic_shielding_tensors.csv"))
mulliken_charges = pd.read_csv(os.path.join("..","data","mulliken_charges.csv"))
potential_energy = pd.read_csv(os.path.join("..","data","potential_energy.csv"))
scalar_coupling_contributions = pd.read_csv(os.path.join("..","data","scalar_coupling_contributions.csv"))
structures = pd.read_csv(os.path.join("..","data","structures.csv"))

In [8]:
magnetic_sheilding_tensors_mulliken_charges_df = pd.merge(
    left=magnetic_sheilding_tensors,
    right=mulliken_charges,
    how="left",
    on=None,
    left_on=['molecule_name','atom_index'],
    right_on=['molecule_name','atom_index'],
    left_index=False,
    right_index=False,
    sort=True,
    suffixes=("_x", "_y"),
    copy=True,
    indicator=False,
    validate=None,
)
magnetic_sheilding_tensors_mulliken_charges_df.to_csv(os.path.join('..','data','joined_data','magnetic_sheilding_tensors_mulliken_charges_df.csv'), index=False)

In [9]:
# magnetic_sheilding_tensors_mulliken_charges_df.head(2)

In [10]:
diapole_moments_potential_energy_df = pd.merge(
    left=diapole_moments,
    right=potential_energy,
    how="inner",
    on=None,
    left_on='molecule_name',
    right_on='molecule_name',
    left_index=False,
    right_index=False,
    sort=True,
    suffixes=("_x", "_y"),
    copy=True,
    indicator=False,
    validate=None,
)
diapole_moments_potential_energy_df.to_csv(os.path.join('..','data','joined_data','diapole_moments_potential_energy_df.csv'), index=False)

In [12]:
# structures

In [13]:
magnetic_sheilding_tensors_mulliken_charges_structures_df = pd.merge(
    left=magnetic_sheilding_tensors_mulliken_charges_df,
    right=structures,
    how="left",
    on=None,
    left_on=['molecule_name','atom_index'],
    right_on=['molecule_name','atom_index'],
    left_index=False,
    right_index=False,
    sort=True,
    suffixes=("_x", "_y"),
    copy=True,
    indicator=False,
    validate=None,
)
magnetic_sheilding_tensors_mulliken_charges_structures_df.to_csv(os.path.join('..','data','joined_data','magnetic_sheilding_tensors_mulliken_charges_structures_df.csv'), index=False)

In [14]:
# magnetic_sheilding_tensors_mulliken_charges_structures_df

In [15]:
magnetic_sheilding_tensors_mulliken_charges_structures_diapole_moments_potential_energy_df = pd.merge(
    left=magnetic_sheilding_tensors_mulliken_charges_structures_df,
    right=diapole_moments_potential_energy_df,
    how="left",
    on=None,
    left_on=['molecule_name'],
    right_on=['molecule_name'],
    left_index=False,
    right_index=False,
    sort=True,
    suffixes=("_x", "_y"),
    copy=True,
    indicator=False,
    validate=None,
)
magnetic_sheilding_tensors_mulliken_charges_structures_diapole_moments_potential_energy_df.to_csv(os.path.join('..','data','joined_data','magnetic_sheilding_tensors_mulliken_charges_structures_diapole_moments_potential_energy_df.csv'), index=False)

In [16]:
magnetic_sheilding_tensors_mulliken_charges_structures_diapole_moments_potential_energy_df

,molecule_name,atom_index,XX,YX,ZX,XY,YY,ZY,XZ,YZ,ZZ,mulliken_charge,atom,x,y,z,X,Y,Z,potential_energy
0,dsgdb9nsd_000001,0,195.3147,0.0000,-0.0001,0.0000,195.3171,0.0007,-0.0001,0.0007,195.3169,-0.535689,C,-0.012698,1.085804,0.008001,0.0000,0.0000,0.0,-40.523680
1,dsgdb9nsd_000001,1,31.3410,-1.2317,4.0544,-1.2317,28.9546,-1.7173,4.0546,-1.7173,34.0861,0.133921,H,0.002150,-0.006031,0.001976,0.0000,0.0000,0.0,-40.523680
2,dsgdb9nsd_000001,2,31.5814,1.2173,-4.1474,1.2173,28.9036,-1.6036,-4.1476,-1.6036,33.8967,0.133922,H,1.011731,1.463751,0.000277,0.0000,0.0000,0.0,-40.523680
3,dsgdb9nsd_000001,3,31.5172,4.1086,1.2723,4.1088,33.9068,1.6950,1.2724,1.6951,28.9579,0.133923,H,-0.540815,1.447527,-0.876644,0.0000,0.0000,0.0,-40.523680
4,dsgdb9nsd_000001,4,31.4029,-4.0942,-1.1793,-4.0944,34.0776,1.6259,-1.1795,1.6260,28.9013,0.133923,H,-0.523814,1.437933,0.906397,0.0000,0.0000,0.0,-40.523680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2358870,dsgdb9nsd_133885,11,28.6323,-0.1148,-2.2990,1.9651,24.5294,-2.4469,-2.0840,0.8863,33.2278,0.078144,H,-1.454004,-0.967309,1.459246,-0.8578,-0.0909,-0.0,-400.760914
2358871,dsgdb9nsd_133885,12,31.2449,6.1929,6.3054,3.8977,29.1150,5.6072,2.3143,3.7461,29.7163,0.099332,H,0.277779,-2.697872,0.195770,-0.8578,-0.0909,-0.0,-400.760914
2358872,dsgdb9nsd_133885,13,33.8789,-3.6278,0.0001,0.6389,25.2816,-0.0000,-0.0001,0.0000,22.4285,0.114018,H,2.515854,-1.151784,0.527369,-0.8578,-0.0909,-0.0,-400.760914
2358873,dsgdb9nsd_133885,14,28.6324,-0.1148,2.2990,1.9652,24.5294,2.4471,2.0840,-0.8863,33.2278,0.078144,H,0.013699,1.199431,-1.680192,-0.8578,-0.0909,-0.0,-400.760914
2358874,dsgdb9nsd_133885,15,31.2450,6.1927,-6.3056,3.8978,29.1149,-5.6073,-2.3143,-3.7461,29.7164,0.099332,H,1.260745,-1.246754,-1.906767,-0.8578,-0.0909,-0.0,-400.760914

In [17]:
scalar_coupling_contributions

,molecule_name,atom_index_0,atom_index_1,type,fc,sd,pso,dso
0,dsgdb9nsd_000001,1,0,1JHC,83.022400,0.254579,1.258620,0.272010
1,dsgdb9nsd_000001,1,2,2JHH,-11.034700,0.352978,2.858390,-3.433600
2,dsgdb9nsd_000001,1,3,2JHH,-11.032500,0.352944,2.858520,-3.433870
3,dsgdb9nsd_000001,1,4,2JHH,-11.031900,0.352934,2.858550,-3.433930
4,dsgdb9nsd_000001,2,0,1JHC,83.022200,0.254585,1.258610,0.272013
...,...,...,...,...,...,...,...,...
4659071,dsgdb9nsd_133884,17,4,2JHC,3.586440,0.019741,0.150477,-0.213205
4659072,dsgdb9nsd_133884,17,5,3JHC,0.674583,-0.007276,0.305078,-0.403388
4659073,dsgdb9nsd_133884,17,6,3JHC,1.337470,-0.028423,0.312240,-0.447920
4659074,dsgdb9nsd_133884,17,7,2JHC,4.800620,0.139202,-0.053102,-0.124710
4659075,dsgdb9nsd_133884,17,8,1JHC,115.975000,0.378277,0.450213,1.130600